config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'
  get 'articulos' => 'posts#index', as: :post_index
  get 'nuevo/post' => 'posts#new', as: :new_post
  get 'post/show/:post_id' => 'posts#show', as: :show_post
  get 'post/edit/:post_id' => 'posts#edit', as: :edit_post
  post 'crear' => 'posts#create', as: :create_post 
  put 'update' => 'posts#update', as: :update_post
  delete 'delete' => 'posts#delete', as: :delete_post

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:edit, :update, :delete]
  
  def index
  	@post = Post.all
  end

  def new
  	@post = Post.new
    @path = create_post_path
    @method = :post
  end

  def edit
    @path = update_post_path
    @method = :put
  end

  def create
  	@posts = Post.new(posts_params)
  	@posts.save
    respond_to do |format|
      format.html { redirect_to post_index_path } 
    end
  end

  def show

  end

  def delete
    @post.destroy
    respond_to do |format|
      format.html { redirect_to post_index_path } 
    end
  end

  def update
    @post.update(posts_params)
    respond_to do |format|
      format.html { redirect_to post_index_path } 
    end
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end

  def posts_params
    params.require(:post).permit(:titulo, :descripcion, :fecha)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nivel</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_tag(@path , method: @method) do %>
	<%= hidden_field_tag :post_id, @post.id %>
	<%= label_tag :titulo, 'titulo'%>
	<%= text_field :post, :titulo, value: @post.titulo %>
	<br>
	<%= label_tag :descripcion, 'descripcion'%>
	<%= text_field :post, :descripcion , value: @post.descripcion %>
	<br>
	<%= label_tag :fecha, 'fecha'%>
	<%= text_field :post, :fecha, value: @post.fecha %>
	<br>
	<%= submit_tag 'enviar'%>
<% end %>

app/views/posts/edit.html.erb
<h2>editar post</h2>
<%= render 'form' %>
<%= link_to 'volver', post_index_path %>

app/views/posts/index.html.erb
<h1>Mis publicaciones</h1>
<table border="1" >
	<tr>
		<td>titulo</td>
		<td>descripcion</td>
		<td>fecha</td>
	</tr>
	<% @post.each do |p| %>
	<tr>
		<td><%= p.titulo %></td>
		<td><%= p.descripcion %></td>
		<td><%= p.fecha %></td>
		<td><%= link_to 'editar', edit_post_path(post_id: p.id) %></td>
		<td><%= link_to 'borrar', delete_post_path(post_id: p.id), method: :delete, data: { confirm: '¿Está seguro que desea borrar el registro?' } %></td>
	</tr>
	<% end %>
</table>
<%= link_to 'crear nuevo post' , new_post_path %>

app/views/posts/new.html.erb
<h1>nuevo post</h1>
	<%= render 'form' %>
<%= link_to 'volver', post_index_path %>

app/views/posts/show.html.erb
<h1>Posts#show</h1>
<p>Find me in app/views/posts/show.html.erb</p>

app/views/posts/update.html.erb
<h2>editat post</h2>
<%= render 'form' %>
<%= link_to 'volver', post_index_path %>